export { setStorageItem } from "./setStorageItem"
export { getStorageItem } from "./getStorageItem"
export { initStorage } from "./initStorage"
export { getAllStorage } from "./getAllStorage"
export { setAllStorage } from "./setAllStorage"