export const LOGO_LIST = [
  "React",
  "NodeJs",
  "Typescript",
  "TailwindCss",
  "Redux",
  "MongoDb",
  "Electron",
  "Stripe",
  "Paypal",
  "Cordova",
  "Socket.io",
  "Styled Components",
  "React-router",
  "React-Bootstrap",
  "Express",
  "Jira",
  "Sass",
  "Git",
  "GitHub",
  "NightWatch",
  "Cucumber Tests",
  "Jest",
  "NPM",
  "MathJs",
  "Visual studio code",
  "Atom",
  "Affinity",
] as const