import React from "react"

const en = (
  <>
    <h2>Terms & Conditions</h2>
    <p>
      The term used "KevinGervais" in these Terms & Conditions refers to our website https://kevingervais.herokuapp.com
      and our KevinGervais iOS and Android app unless otherwise defined in this
      Privacy Policy.
    </p>
    <p>
      As you browse KevinGervais, these terms will be
      automatically applied to you - so you should make sure that
      that you read them carefully before using the application. You are not
      allowed to copy, or modify the application, any part of the application
      or our trademarks in any way. You may not attempt to
      extract the source code of the Application, and you may not attempt to
      attempt to translate the application into other languages, or
      make derivative versions. The application itself and all commercial,
      copyright, database rights and other intellectual property rights,
      the property rights related to it all belong to
      Kevin Gervais
    </p>

    <p>
      Kevin Gervais is committed to making KevinGervais
      is as useful and effective as possible. For this reason, we
      reserve the right to make changes to KevinGervais at any time and for any reason.
    </p>
    <p>
      KevinGervais stores and processes personal data
      that you have provided to us, in order to provide
      our service.
    </p>
    <p>
      You should be aware that there are certain things that
      Kevin Gervais does not take responsibility for.
      Some functions of KevinGervais will require KevinGervais to have an active
      Internet connection. The connection may be Wi-Fi or
      provided by your mobile network provider, but
      Kevin Gervais cannot assume responsibility for the application not working at full functionality if you do not have
      access to Wi-Fi.
    </p>
    <p />
    <p>
      In the same vein, Kevin Gervais cannot always
      take responsibility for how you use KevinGervais, i.e.
      you need to make sure your device stays charged - if it
      battery and you can't turn it on to enjoy the Service, Kevin Gervais
      service, Kevin Gervais cannot be held responsible.
      responsible.
    </p>
    <p>
      With respect to Kevin Gervais's liability regarding
      your use of KevinGervais, when using it, it is important to keep in mind that
      important to keep in mind that, while we strive to ensure that it is updated
      ensure that it is updated and correct at all times, we do
      rely on third parties to provide us with information so that
      we can make it available to you.
      Kevin Gervais disclaims any responsibility for any loss,
      direct or indirect that you encounter on any third party dependent functionality in the application.
    </p>
    <p>
      At some point, we may want to update KevinGervais
      Kevin Gervais does not promise that
      he will always update KevinGervais to make it relevant to you.
      We may also wish to cease providing KevinGervais, and may terminate use at any time without
      use at any time without notice. Unless otherwise specified by us, upon termination
      the rights and licenses granted to you under these Terms
      will terminate;
    </p>

    <p> <strong>Non-compliance with these terms and conditions </strong> </p>
    <p>
      KevinGervais gives itself the discretion to delete the account of those who abuse KevinGervais's terms and conditions.
    </p>
    <p> <strong>Changes to these terms and conditions</strong> </p>
    <p>
      We may update our terms and conditions
      from time to time. Thus, you are advised to check this page
      periodically for any changes. We will
      notify you of any changes by posting the new Terms and
      Terms and Conditions on this page. These changes are effective
      immediately upon posting on this page.
    </p>
    <p> <strong>Contact Us</strong> </p>
    <p>
      If you have any questions or suggestions about
      our Terms and Conditions, please feel free to contact us through the means offered in the contact us section of our website
    </p>
    <p>
      This terms and conditions page was generated by
      <a rel="noopener noreferrer" href="https://app-privacy-policy-generator.firebaseapp.com/" target="_blank">
        Application Privacy Rule Generator
      </a>
    </p>
  </>
)

export default en
