export { APP_VERSION } from "./APP_VERSION"
export * from "./FILE_ACCEPT"
export { IS_DESKTOP } from "./IS_DESKTOP"
export { IS_DEV } from "./IS_DEV"
export { IS_ANY_IOS } from "./IS_ANY_IOS"
export { OS } from "./OS"
export { IS_CORDOVA } from "./IS_CORDOVA"
export { REQUIRED_TW_CLASS_LIST } from "./REQUIRED_TW_CLASS_LIST"