name: Deploy Android app

on:
  push:
    branches: release_/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
      - name: upload to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: app.kevingervais.com
          releaseFile: mobile/app-release.apk
          track: beta
